### ISSUE TITLE
docker-coffea-dask

### ISSUE THREAD

**Issue by nsmith-** [CoffeaTeam/docker-coffea-dask#1]
Do we want to make a new repo in this team named `docker-coffea-dask` and set up the same auto-update dependency, chained off of base? Or put it in this repo and make the CI rebuild all at once? What should be added? Here is what I had previously: https://github.com/CoffeaTeam/coffea-farm/blob/master/docker/coffea-dask/Dockerfile#L14-L28 
We'll need to add condor python deps both for casa and what @lgray was doing for LPC

**Comment by lgray** [comment]
A further question on this - do we want a separate repository for the corresponding dask client environment (which will have joqueue and other goodies)? or just publish the client/worker pair from here?

**Comment by oshadura** [comment]
@lgray I will experiment with `docker-coffea-dask` image and let you know how will be better to proceed.
Basically to put dask-jobqueue will be super easy but to configure HTCondor I suspect not that easy....

My next step will be to totally rewrite `coffea-casa` images based on  `docker-coffea-dask`, having the possibility to properly generated HTCondor Configs.
