### ISSUE TITLE
coffea-dask has not picked up coffea 0.7.6

### ISSUE THREAD

**Issue by lgray** [CoffeaTeam/docker-coffea-dask#39]
as in title!

**Comment by oshadura** [comment]
@lgray it looks like it is not happy of two separate dispatch events (for cc7 and miniconda images). Looking into it!

**Comment by oshadura** [comment]
I hope it should be fixed by https://github.com/CoffeaTeam/docker-coffea-base/commit/c6dfbccc63aa06d8bd48eb736ebcf9c816f8cb54

**Comment by lgray** [comment]
Fixed in #43 + patches to handle the debian and centos7 images separately.
