### ISSUE TITLE
Add dask-jobqueue

### ISSUE THREAD

**Issue by nsmith-** [CoffeaTeam/docker-coffea-dask#7]
If https://jobqueue.dask.org/en/latest/install.html is added to this image, it becomes a convenient entrypoint for users with an existing batch cluster that want to run coffea jobs. FYI @andrzejnovak

**Comment by andrzejnovak** [comment]
For those of use with conda installs, it would still be easier if it was a req

**Comment by oshadura** [comment]
@andrzejnovak I install everything via conda because in such a way we can have automatic version update (checking new released versions in conda)

**Comment by andrzejnovak** [comment]
I think there was some miscommunication. I was originally proposing to have dask_jobque pulled with reqs when installing `coffea[dask]`

**Comment by nsmith-** [comment]
This is more or less a separate issue from that one. Here we are trying to provide a good base singularity image for sites where user home is not mounted.

**Comment by oshadura** [comment]
@andrzejnovak we have two different images, one build on top of the other.

The first one https://github.com/CoffeaTeam/docker-coffea-base is released automatically when is released a new version of `coffea`. The second one https://github.com/CoffeaTeam/docker-coffea-dask which is based on the first one is allowing to release automatically Docker image each time a new version of dask/distributed is released.

`coffea[dask]` can be pulled from pip while here we are using conda. We inspected which packages are pulled with `coffea[dask]` and what we have in the image currently and it is absolutely the same :)

**Comment by oshadura** [comment]
@andrzejnovak did you already try this image? (we use it as well for `coffea-casa` and it nicely works :) )
